// Generated by CoffeeScript 1.6.3
(function() {
  define('helpers', ['md5'], function(md5) {
    var helpers;
    helpers = {
      arrayRemove: function(from, to) {
        var rest;
        rest = this.slice((to || from) + 1 || this.length);
        this.length = (from < 0 ? this.length + from : from);
        return this.push.apply(this, rest);
      },
      cloneObj: function(obj) {
        var attr, copy;
        if (null === obj || "object" !== typeof obj) {
          return obj;
        }
        copy = obj.constructor();
        for (attr in obj) {
          if (obj.hasOwnProperty(attr)) {
            copy[attr] = obj[attr];
          }
        }
        return copy;
      },
      getEventCoords: function(e) {
        if (e.clientX) {
          return {
            x: e.clientX,
            y: e.clientY
          };
        } else {
          return {
            x: e.gesture.center.pageX,
            y: e.gesture.center.pageY
          };
        }
      },
      timeIn: function(name) {
        return App.debug.time && console.time(name);
      },
      timeOut: function(name) {
        return App.debug.time && console.timeEnd(name);
      },
      genHash: function() {
        return md5((new Date) + (new Date).getMilliseconds() + Math.random(9999999999999) + Math.random(9999999999999) + Math.random(9999999999999));
      },
      getRandom: function(min, max) {
        return Math.floor((Math.random() * ((max + 1) - min)) + min);
      },
      stopEvent: function(e) {
        e.preventDefault();
        e.stopPropagation();
        return false;
      }
    };
    return helpers;
  });

}).call(this);
