// Generated by CoffeeScript 1.6.2
(function() {
  define('helpers', ['two', 'md5'], function(Two, md5) {
    var helpers;

    helpers = {
      arrayRemove: function(from, to) {
        var rest;

        rest = this.slice((to || from) + 1 || this.length);
        this.length = (from < 0 ? this.length + from : from);
        return this.push.apply(this, rest);
      },
      getEventCoords: function(e) {
        return {
          x: e.gesture.center.pageX,
          y: e.gesture.center.pageY
        };
      },
      timeIn: function(name) {
        return console.time(name);
      },
      timeOut: function(name) {
        return console.timeEnd(name);
      },
      genHash: function() {
        return md5((new Date) + (new Date).getMilliseconds() + Math.random(9999999999999) + Math.random(9999999999999) + Math.random(9999999999999));
      },
      getRandom: function(min, max) {
        return Math.floor((Math.random() * ((max + 1) - min)) + min);
      },
      stopEvent: function(e) {
        e.preventDefault();
        e.stopPropagation();
        return false;
      },
      makePoint: function(x, y) {
        var h, v;

        h = this.getRandom(0, 10);
        if (arguments.length <= 1) {
          y = x.y;
          x = x.x;
        }
        if (h === 5) {
          v = new Two.Anchor(x, y, x * 2, y * 2, x * 1.5, y * 1.5, Two.Commands.curve);
        } else {
          v = new Two.Anchor(x, y);
        }
        return v;
      }
    };
    return helpers;
  });

}).call(this);
