// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('event', ['backbone', 'underscore', 'helpers', 'port'], function(B, _, helpers, Port) {
    var Event, _ref;

    Event = (function(_super) {
      __extends(Event, _super);

      function Event() {
        _ref = Event.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      Event.prototype.defaults = {
        size: 2,
        type: 'event'
      };

      return Event;

    })(Port);
    return Event;
  });

}).call(this);

/*
//@ sourceMappingURL=event.map
*/
