// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define('event', ['backbone', 'underscore', 'helpers', 'port'], function(B, _, helpers, Port) {
    var Event;

    Event = (function(_super) {
      __extends(Event, _super);

      function Event(o) {
        this.o = o != null ? o : {};
        console.log('event init');
      }

      return Event;

    })(Port);
    return Event;
  });

}).call(this);

/*
//@ sourceMappingURL=event.map
*/
